### ISSUE TITLE
Issue with generated javascript array (holidays, futures_pending, futures_approved)

### ISSUE THREAD

**Issue by bplessis** [sayoun/pyvac#17] opened 2016-02-05 10:45 UTC
In current browsers (firefox 43, chrome 48) the generated date array trigger a blocking error:

with chrome: "Uncaught SyntaxError: Unexpected token ILLEGAL"
with firefox: "SyntaxError: identifier starts immediately after numeric literal"

Most probably due to the suffix "L" in the numeric values:
var holidays = [1451606400000L, 1459123200000L, ... ];

I wasn't able to find what generated this 'L' however ...

**Comment by sayoun** [comment] 2016-02-05 12:57
Cannot reproduce it on chromium 48 or iceweasel 43. 

Usually the L suffix is displayed when we want to display a string for a long number, but here we only give the jinja template a list of longs.

So the root cause can be either the python version or the jinja2 version I guess. What versions are you using ?

**Comment by bplessis** [comment] 2016-02-05 13:13
I used python 2.7.9 with Jinja2-2.8 in a virtualenv

**Comment by bplessis** [comment] 2016-02-06 20:04
Problème lié à l'OS 32bits utlisé, les "timestamps milliseconds" depassent l'entier 32bits et python 2.7 les stocke dans des longinteger, le suffix L est l'affichage natif de ces objets

**Comment by sayoun** [comment] 2016-02-08 07:52
Fixed in PR #20 20

**Closed by sayoun** 2016-02-08 07:52 UTC
